"""Collection context exports."""

from .application import (
    DetailPageWorker,
    DetailPageWorkerResult,
    NavigationHandler,
    PaginationHandler,
    ReplayNavigationResult,
    ResultAggregator,
    ScriptGenerator,
    URLCollector,
    URLExtractor,
    build_navigation_task_plan,
    collect_detail_urls,
    generate_crawler_script,
    run_field_pipeline,
)
from .domain import (
    CollectionRun,
    FieldBinding,
    FieldDefinition,
    PageResult,
    VariantResolver,
    XPathPattern,
    XPathSegment,
    append_page_result,
    build_xpath_fallback_chain,
    normalize_xpath,
    strip_indexes,
    xpath_similarity,
    xpath_stability_score,
)

__all__ = [
    "CollectionRun",
    "DetailPageWorker",
    "DetailPageWorkerResult",
    "FieldBinding",
    "FieldDefinition",
    "NavigationHandler",
    "PageResult",
    "PaginationHandler",
    "ReplayNavigationResult",
    "ResultAggregator",
    "ScriptGenerator",
    "URLCollector",
    "URLExtractor",
    "VariantResolver",
    "XPathPattern",
    "XPathSegment",
    "append_page_result",
    "build_navigation_task_plan",
    "build_xpath_fallback_chain",
    "collect_detail_urls",
    "generate_crawler_script",
    "normalize_xpath",
    "run_field_pipeline",
    "strip_indexes",
    "xpath_similarity",
    "xpath_stability_score",
]
