from __future__ import annotations

from autospider.composition.legacy.pipeline.aggregator import ResultAggregator
from autospider.composition.legacy.pipeline.finalization import (
    PipelineFinalizationContext,
    PipelineFinalizationDependencies,
    PipelineFinalizer,
    build_execution_id,
    build_record_summary,
    build_run_record,
    classify_pipeline_result,
    cleanup_output_draft_skill,
    commit_items_file,
    finalize_task_from_record,
    find_output_draft_skill,
    load_persisted_run_records,
    persist_pipeline_records,
    prepare_fields_config,
    prepare_pipeline_output,
    promote_pipeline_skill,
    promote_staged_output,
    should_promote_skill,
    strip_draft_markers_from_skill_content,
    write_summary,
)

__all__ = [
    "PipelineFinalizationContext",
    "PipelineFinalizationDependencies",
    "PipelineFinalizer",
    "ResultAggregator",
    "build_execution_id",
    "build_record_summary",
    "build_run_record",
    "classify_pipeline_result",
    "cleanup_output_draft_skill",
    "commit_items_file",
    "finalize_task_from_record",
    "find_output_draft_skill",
    "load_persisted_run_records",
    "persist_pipeline_records",
    "prepare_fields_config",
    "prepare_pipeline_output",
    "promote_pipeline_skill",
    "promote_staged_output",
    "should_promote_skill",
    "strip_draft_markers_from_skill_content",
    "write_summary",
]
